Repository aeon-toolkit/aeon-neuro, pull requests merged in 2024-07, with the labels that each got.

#58 [ENH] add riemannian distance functions between matrices
  aeon_neuro/_wip/distances/_riemannian_matrix.py
  aeon_neuro/_wip/distances/tests/test_riemannian_matrix.py
  examples/_wip/distances/riemannian_matrix.ipynb
Labels: enhancement, examples

#59 [DOC,MNT] Documentation and testing for epoching.py
  aeon_neuro/transformations/epoching.py
  aeon_neuro/transformations/tests/test_epoching.py
Labels: documentation, maintenance

#61 [MNT,DOC] Set up webpage and Read the Docs
  .readthedocs.yml
  aeon_neuro/__init__.py
  docs/Makefile
  docs/_static/css/custom.css
  docs/api_reference.md
  docs/api_reference/benchmarking.rst
  docs/api_reference/data.rst
  docs/api_reference/data_scripts.rst
  docs/api_reference/examples.rst
  docs/api_reference/transformations.rst
  docs/api_reference/utils.rst
  docs/conf.py
  docs/datasets.md
  docs/images/logo/aeon-favicon.ico
  docs/images/logo/aeon-logo-blue-2-compact.png
  docs/index.md
  docs/installation.md
  docs/make.bat
  docs/papers.md
  pyproject.toml
Labels: documentation, maintenance

#63 Release v0.0.1
  README.md
  docs/changelog.md
  docs/changelogs/v0.0.1.md
  docs/index.md
Labels: maintenance, release

#65 [MNT] Fix release v0.0.1
  CHANGELOG.md
  MANIFEST.in
Labels: maintenance, release
